In [1]:
import numpy as np

In [19]:
#Training data
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
             [1,1,1]])
y = np.array([[0],
            [1],
            [1],
            [0]])
np.random.seed(1)

In [20]:
y

array([[0],
       [1],
       [1],
       [0]])

In [27]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [22]:
#Randomly intilize weights 
#Hidden layer1 has 3 inputs and 4 neurons/outputs
weights0 = 2*np.random.random((3,4))-1
#Hidden layer2 has 4 inputs and 1 neuron/output
weights1 = 2*np.random.random((4,1))-1

In [23]:
weights0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [24]:
weights1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [25]:
#Sigmoid function
def sigmoid( x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [26]:
#training the network

for i in range(80000):
    #Foward Propagation
    #Input layer
    layer0 = X
    #Hidden layer
    layer1 = sigmoid(np.dot(layer0,weights0))
    #Output layer
    layer2 = sigmoid(np.dot(layer1,weights1))
    
    #calculate error -> just used a simple cost function 
    layer_2_error = y-layer2
    
    if i%10000 == 0:
        print("Error: {}".format(str(np.mean(np.absolute(layer_2_error)))))
        
    #Back Propagation
    layer2_delta = layer_2_error*sigmoid(layer2,deriv=True)
    #print(layer2_delta)
    layer1_error = layer2_delta.dot(weights1.T)
    #print(layer1_error)
    layer1_delta = layer1_error*sigmoid(layer1, deriv=True)
    #print(layer1_delta)
    
    #Update the weights 
    learningRate = .1
    weights1 = weights1+layer1.T.dot(layer2_delta)*learningRate
    weights0 = weights0+layer0.T.dot(layer1_delta)*learningRate
    
    

Error: 0.4964100319027255
Error: 0.042888017000115804
Error: 0.02409899422852161
Error: 0.018110652146797836
Error: 0.014987616272210912
Error: 0.013014490538142583
Error: 0.011631240177791713
Error: 0.010595837575746213


In [10]:
layer1

array([[6.12903942e-01, 1.45168200e-01, 9.14695069e-01, 9.93587617e-01],
       [2.20100125e-01, 7.55049236e-04, 1.91707686e-02, 8.81134673e-01],
       [9.87129756e-01, 8.66007539e-01, 2.60148164e-02, 7.72181015e-01],
       [9.31837582e-01, 2.79537908e-02, 4.86845534e-05, 1.39529364e-01]])

In [34]:
X_test_input = np.array([[0,1,1],
            [1,0,1],
             [0,0,1]])

In [35]:
layer0 = X_test_input
layer1 = sigmoid(np.dot(layer0,weights0))
test_output = sigmoid(np.dot(layer1,weights1))

In [36]:
test_output

array([[0.98974527],
       [0.99107044],
       [0.00801053]])